import type { Metadata } from "next";
import "./globals.css";
import PrelineScript from "./components/PrelineScript";
import { PostProvider } from "./context/PostContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrelineScript />
      <body>
        <PostProvider>
          <div>{children}</div>
        </PostProvider>
      </body>
    </html>
  );
}
